//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningScheduleBokkingManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingScheduleManagementDBEntities2 : DbContext
    {
        public BookingScheduleManagementDBEntities2()
            : base("name=BookingScheduleManagementDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLEANINGSCHEDULE> CLEANINGSCHEDULEs { get; set; }
        public virtual DbSet<GROUP> GROUPs { get; set; }
        public virtual DbSet<RESIDENT> RESIDENTS { get; set; }
    }
}
