//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningScheduleBokkingManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLEANINGSCHEDULE
    {
        public int WeekNumber { get; set; }
        public int SlotNumber { get; set; }
        public Nullable<int> Resident_Id { get; set; }
        public int Group_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> Is_Cleaned { get; set; }
        public Nullable<bool> Is_Verified { get; set; }
        public bool Is_FullDay { get; set; }
        public string Theme_Colour { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual RESIDENT RESIDENT { get; set; }
    }
}
